### ISSUE TITLE
Dropped items not rendered

### ISSUE THREAD

**Issue by w4lll** [shmoobalizer/DevArt_Classic#8]
When dropping items, the item that dropped is not rendered (empty). Blocks (item drops) is rendered. This also happens on vanilla minecraft.

**Comment by Aleksandra0056** [comment]
I'm not sure, but other people from Planet Minecraft are connecting this issue with shaders. I think, that it would be probably caused by shaders from other loaded Resource Packs or mods like OptiFine or Sodium. Try disabling all OptiFine/Sodium shaders & all other resource packs (except Beta Continuum) and tell me if the issue persists.

And, better would be to keep this issue open, so other people would easier see, that it is still an unsolved problem.

**Comment by w4lll** [comment]
Turning on the fog (dont set the fog to off) fixes the issue in optifine, sodium also works fine.

> I'm not sure, but other people from Planet Minecraft are connecting this issue with shaders. I think, that it would be probably caused by shaders from other loaded Resource Packs or mods like OptiFine or Sodium.

i guess the problem is either the shaders folder or maybe optifine/iris shaders. i didn't use optifine/iris shaders because it lags and for some reason the item not rendered even with vanilla in default settings. i guess the creator fixes that issue.
